#!/bin/bash -e

if [ -d env ]; then
  source env/bin/activate
  rm -rf build

  case "`uname`" in
    "Darwin")
      PLATFORM="Mac";;
    *)
      PLATFORM="`uname`";;
  esac
  VERSION=`cat grow/VERSION`
  FILENAME="Grow-SDK-${PLATFORM}-${VERSION}.zip"

  pyinstaller grow.spec
  chmod +x dist/grow
  cd dist
  zip -r FILENAME grow
  cd ..
  echo "Built: dist/${FILENAME}"
  ./dist/grow

  deactivate
else
  echo 'Run ./scripts/setup first.'
  exit 1
fi
