#!/bin/bash

pip --version > /dev/null || {
  echo "pip not installed. Trying to install pip..."
  sudo easy_install pip
}

virtualenv --version > /dev/null || {
  echo "virtualenv not installed. Trying to install virtualenv..."
  sudo pip install virtualenv
}

virtualenv env
source env/bin/activate
pip install -r requirements.txt
deactivate
