#!/bin/bash -e

exists() {
  type -t "$1" > /dev/null 2>&1; 
}

pip --version > /dev/null || {
  echo "pip not installed. Trying to install pip..."
  sudo easy_install pip
}

virtualenv --version > /dev/null || {
  echo "virtualenv not installed. Trying to install virtualenv..."
  sudo pip install virtualenv
}

echo "Trying to install libyaml..."
if exists brew; then
  brew install libyaml || {
    echo " Error installing libyaml with brew."
    echo " Try installing from source: http://pyyaml.org/wiki/LibYAML"
  }
elif exists apt-get; then
  sudo apt-get install libyaml-dev
else
  echo " You must install libyaml from source: http://pyyaml.org/wiki/LibYAML"
fi

virtualenv env
source env/bin/activate
pip install -r requirements.txt
deactivate

# Avoid libyaml issues on Mac by explicitly reinstalling.
source env/bin/activate
pip install --upgrade PyYAML==3.10
deactivate
