#!/bin/bash

if [ -d env ]; then
  source env/bin/activate
  if [ $@ ]; then
    nosetests \
      -v \
      --rednose \
      --with-coverage \
      --cover-erase \
      --cover-html \
      --cover-html-dir=htmlcov \
      --cover-package=grow \
      $@
  else
    nosetests \
      -v \
      --rednose \
      --with-coverage \
      --cover-erase \
      --cover-html \
      --cover-html-dir=htmlcov \
      --cover-package=grow \
      grow/
  fi
  deactivate
else
  echo 'Run ./scripts/setup first.'
  exit 1
fi
