#!/bin/bash -e

if [ -d env ]; then
  source env/bin/activate

  if [ `git rev-parse --abbrev-ref HEAD` != "master" ]; then
    echo 'Releases must be made from "master".'
    exit 1
  fi

  git pull origin master
  ./scripts/test

  python setup.py sdist upload
  rm -rf *.egg-info

  deactivate
else
  echo 'Run ./scripts/setup first.'
  exit 1
fi
